# Generated by Django 3.2.9 on 2021-12-02 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('necktieapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='address',
            new_name='town',
        ),
        migrations.RemoveField(
            model_name='address',
            name='buildingName',
        ),
        migrations.RemoveField(
            model_name='address',
            name='district',
        ),
        migrations.RemoveField(
            model_name='address',
            name='roomOrFloor',
        ),
        migrations.AlterField(
            model_name='fee',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
