# Generated by Django 3.2.9 on 2021-12-02 19:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('necktieapp', '0004_auto_20211202_1853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='contacts',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='schedules',
        ),
        migrations.AddField(
            model_name='contact',
            name='doctor',
            field=models.ForeignKey(default=601, on_delete=django.db.models.deletion.CASCADE, to='necktieapp.doctor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='doctor',
            field=models.ForeignKey(default=601, on_delete=django.db.models.deletion.CASCADE, to='necktieapp.doctor'),
            preserve_default=False,
        ),
    ]
